### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by wouterds** [dracula/pygments#4]
Instructions are kinda vague "download and unzip". But where do I place those files? What am I supposed to do with the files? If  run `python dracula.py` (which should be called install.py or something if that's what it does) and run `pygmentize -g -O style=dracula package.json` after it's still the default theme. Without specifying the theme (`pygmentize -g package.json`) it still shows up with the default theme.

How do I get this working? 😅

**Comment by wouterds** [comment]
I managed to get it working by copying `dracula.py` to `/usr/local/lib/python3.7/site-packages/Pygments-2.5.2-py3.7.egg/pygments/styles`.

**Comment by danielcs88** [comment]
How would this work in the case of an Anaconda setup?

**Comment by danielcs88** [comment]
If it is already installed, when attempting to install via `pip`:

```shell
❯ ~ pip install Pygments
```
leads to this message

> ```
> Requirement already satisfied: Pygments in ./anaconda3/lib/python3.7/site-packages (2.7.4)                              /2.4s
> ```

In my case since I have a setup with Anaconda it was `/home/daniel/anaconda3/lib/python3.7/site-packages/pygments/styles` but it all depends on where Pygments has its folder.

Then copy `dracula.py` into the `styles` folder.

Finally, run the [instructions](https://draculatheme.com/pygments) here which are:

```shell
pygmentize -S dracula -f html > dracula.css
```

Done.
