### ISSUE TITLE
unable to install as the installation info is way too vague.

### ISSUE THREAD

**Issue by nerd190** [dracula/pygments#5]
(Quotes are from your website)

> Download the zip & unzip them.

**And then what?** where do I place them?

> You can generate the CSS stylesheet (also included in this repository) by using the included dracula.py file and the Pygments Command Line Interface:

**If the CSS stylesheet is already included, why do I need to generate it again using dracula.py?** which Is also very confusing as:

> Run the following command on your terminal:
> pygmentize -S dracula -f html > dracula.css

**This command doesnt use dracula.py at all** so how do I use dracula.py? its not executable so I assume that I need to place it somewhere, if so, where?
Also confused as running the above command from within the cloned repo doesnt work at all, the error says:
`
Could not find style module 'dracula'.
`

Thank you in advance for any help you can give, its appreciated.

**Comment by danielcs88** [comment]
@5c0tt-b0t #5 

If it is already installed, when attempting to install via `pip`:

```shell
❯ ~ pip install Pygments
```
leads to this message

> ```
> Requirement already satisfied: Pygments in ./anaconda3/lib/python3.7/site-packages (2.7.4)                              /2.4s
> ```

In my case since I have a setup with Anaconda it was `/home/daniel/anaconda3/lib/python3.7/site-packages/pygments/styles` but it all depends on where Pygments has its folder.

Then copy `dracula.py` into the `styles` folder.

Finally, run the [instructions](https://draculatheme.com/pygments) here which are:

```shell
pygmentize -S dracula -f html > dracula.css
```

Done.

**Comment by zenorocha** [comment]
Can you send a pull request? The instructions are located on the INSTALL.md file.
